### ISSUE TITLE
Good bye react-native-gifted-spinner!

### ISSUE THREAD

**Issue by rturk** [FaridSafi/react-native-gifted-spinner#14]
Thank you **React-Native-Gifted-Spinner** for all the fun we had while waiting lazy APIs load data from the backend..

[ActivityIndicator](https://facebook.github.io/react-native/docs/activityindicator.html) you have big shoes to fill..

**Comment by FaridSafi** [comment]
Thank you @rturk :)

**Comment by ryanhanwu** [comment]
Many thanks @rturk

**Comment by mdrajib001** [comment]
Many Many Thanks rturk. It saved my time to integrate new package.
