### ISSUE TITLE
Check out what I did with this!

### ISSUE THREAD

**Issue by niftylettuce** [FaridSafi/react-native-gifted-spinner#2]
https://github.com/niftylettuce/react-native-loading-spinner-overlay

**Comment by FaridSafi** [comment]
Great! Did you forget to add react-native-gifted-spinner in package.json as dependency ?

**Comment by niftylettuce** [comment]
Haha wow I did... thank you :laughing:

**Comment by niftylettuce** [comment]
Published v0.0.5 and added deprecation notice, thanks @FaridSafi
