### ISSUE TITLE
Upgrade import to RN0.25+

### ISSUE THREAD

**Issue by rturk** [FaridSafi/react-native-gifted-spinner#7]
Starting in RN 25 React Native import wil change:

Requiring React API from react-native will be deprecated:
https://github.com/facebook/react-native/releases/tag/v0.25.1

Instead of:

`import React, { Component, View } from 'react-native';
`

you should now:

```
import React, { Component } from 'react';
import { View } from 'react-native';
```

You can also try this codemod built by the community to automatically rewrite all the imports.
https://github.com/sibeliusseraphini/codemod-RN24-to-RN25

**Comment by rturk** [comment]
Fix in this PR https://github.com/FaridSafi/react-native-gifted-spinner/pull/5

**Comment by sibelius** [comment]
fixed on master
